project:
  group: slipper
  name: slipper

service:
  port: 8808
  context-path: /slipper

database:
  ip: localhost
  port: 3306
  name: im
  username: root
  password: 111111

druid:
  url-pattern: /druid/*
  username:
  password:

token:
  expire: 36000

redis:
  host: localhost
  port: 6379
  password:

netty:
  port: 8809
  url: ws://localhost:${netty.port}/websocket/{token}
